#SPDX-License-Identifier: MIT-0
---
# tasks file for kubernetes
- name: Load kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Set sysctl entries
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward


- name: Add kubernetes repository
  ansible.builtin.yum_repository:
    name: Kubernetes
    description: kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key
    gpgcheck: true
    enabled: true
    exclude: kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: Put SELinux in permissive mode
  ansible.posix.selinux:
    state: permissive
    policy: targeted

- name: install kubernetes
  dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - python3-pip
      - python3-wheel
    disable_excludes: Kubernetes

- name: Install Kubernetes python library
  pip:
    name: kubernetes

- name: Enable kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
