#SPDX-License-Identifier: MIT-0
---
# tasks file for containerd

- name: Install containerd
  unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.7.3/containerd-1.7.3-linux-arm64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Download containerd service file
  get_url:
    url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
    dest: /usr/lib/systemd/system/containerd.service

- name: Create a containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Create a containerd config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

- name: Set Systemd cgroup driver for containerd
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Set pause container image
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'sandbox_image = "registry.k8s.io\/pause:3.8"'
    replace: 'sandbox_image = "registry.k8s.io\/pause:3.9"'

- name: Install runc
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.1.8/runc.arm64
    dest: /usr/local/sbin/runc
    mode: '0755'

- name: Create a cni bin directory
  file:
    path: /opt/cni/bin
    state: directory

- name: Install CNI plugins
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-arm-v1.3.0.tgz
    dest: /opt/cni/bin
    remote_src: yes

- name: Start containerd service
  systemd_service:
    state: started
    name: containerd
    enabled: true
    daemon_reload: true


